---
- hosts: localhost
  connection: local
  tasks:
  - name: creating a service for ecs cluster
    ecs_service:
      aws_access_key: "{{ access }}"
      aws_secret_key: "{{ secret }}"
      region: us-east-1
      state: present
      name: test-service
      cluster: raviteja
      task_definition: "{{ name }}"
      desired_count: 3
      deployment_configuration:
        minimum_healthy_percent: 75
        maximum_percent: 150
