---
- hosts: localhost
  connection: local
  tasks:
  - name: creating task definition for jenkins
    ecs_taskdefinition:
      aws_access_key: "AKIAIGTCNJJQ63SXETEA"
      aws_secret_key: "dUrS1wCkmLe6qrAhmnLG0JYjnjM2KySR26r1oj8p"
      region: us-east-1
      containers:
      - name: sample-app
        cpu: 512
        essential: true
        image: "yadaraviteja/node-web-app:latest"
        memory: 512
        portMappings:
        - containerPort: 8080
          hostPort: 49164
        #logConfiguration:
         # logDriver: awslogs
         # options:
           # awslogs-group: ecs/new-node
           # awslogs-region: us-east-1
     # task_role_arn: "arn:aws:iam::318896727843:role/ecsTaskExecutionRole"
      state: present
      family: "test"
